### ISSUE TITLE
Issue in "processing_data.py"... TypeError: '<' not supported between instances of 'numpy.longdouble' and 'int'

### ISSUE THREAD

**Issue by RawbyTheSheeth** [joaohenry23/GOES#1]
In line 276, `num2date` is fails for me when data is a zero dimensional numpy array. This occurs when I read the file:
`file = 'OR_ABI-L2-CMIPF-M6C14_G16_s20200802050177_e20200802059485_c20200802059592.nc'`

I get:
`TypeError: '<' not supported between instances of 'numpy.longdouble' and 'int'`

For my workaround, I simply added the line:
`data = data if np.array(data).ndim > 0 else [data.tolist()] ` 
right after `data` is first assigned in line 271. It hasn't broken anything else for me yet.

**Comment by joaohenry23** [comment]
@RawbyTheSheeth  thanks so much for your contribution.
I would like understand why I did not identify this problem before, please, could you write the lines of your code that produce this fail?

**Comment by RawbyTheSheeth** [comment]
This snippet is enough to reproduce the error for me. It's based on the "reads_one_file.ipynb" example. Hopefully I'm not just misunderstanding something or reading a file I'm not supposed to! 

I just realized in my first comment I failed to mention that the line I added was in `processing_data.py`. The variable `data` is a zero-dimensional array when I run the code below, which breaks the program when it calls `                        data = num2date(data, parameter.units, 'standard', only_use_cftime_datetimes=False, only_use_python_datetimes=True)
` in line 276.

```
import GOES

filepath = 'C:/Users/<username>/temp/'

flist = GOES.download('goes16', 'ABI-L2-CMIPF',
                      DateTimeIni = '20200320-203000', DateTimeFin = '20200320-203100', 
                      channel = ['08-10','13','14'], path_out=filepath)

file = 'OR_ABI-L2-CMIPF-M6C08_G16_s20200802030177_e20200802039485_c20200802039575.nc'

ds = GOES.open_dataset(filepath+file)

CMI, LonCen, LatCen = ds.image('CMI')
```

It gives this error
```
ds.image('CMI')
Traceback (most recent call last):

  File "<ipython-input-3-69e1dfe17e4f>", line 1, in <module>
    ds.image('CMI')

  File "C:\ProgramData\Anaconda3\lib\site-packages\GOES\processing\processing_data.py", line 450, in image
    dict_Field['t'] = self.variable('t')

  File "C:\ProgramData\Anaconda3\lib\site-packages\GOES\processing\processing_data.py", line 276, in variable
    data = num2date(data, parameter.units, 'standard', only_use_cftime_datetimes=False, only_use_python_datetimes=True)

  File "src\cftime\_cftime.pyx", line 584, in cftime._cftime.num2date

  File "src\cftime\_cftime.pyx", line 382, in cftime._cftime.cast_to_int

TypeError: '<' not supported between instances of 'numpy.longdouble' and 'int'
```

**Comment by joaohenry23** [comment]
@RawbyTheSheeth thanks so much for write your code.
I downloaded the file again, ran the code and had no error.
![image](https://user-images.githubusercontent.com/53101118/176337982-39cd5b89-14b9-43e4-8556-97bca8e6a323.png)

I reckon that the cftime could be problem. Please, you could execute in your python the follow lines and write the return:
```
import sys
sys.version

import cftime
cftime.__version__
```
Sorry for abusing your kindness.

**Comment by RawbyTheSheeth** [comment]
Sorry for the delay. I was away from my computer when I first received this, and I forgot to check back!

```
In [3]: import sys
   ...: sys.version
Out[3]: '3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]'

In [4]: 
   ...: import cftime
   ...: cftime.__version__
Out[4]: '1.6.0'
```

**Comment by joaohenry23** [comment]
@RawbyTheSheeth, sorry for the delay, I've been very busy.
Based on your output, I believe the lines were executed in the python of your system. The word "default" after running "sys.version" makes me think so. You could run the following lines in python where you ran "reads_one_file.ipynb" (I think it was in the python of anaconda):

```
import sys
sys.version

import netCDF4
netCDF4.__version__

import cftime
cftime.__version__

from netCDF4 import num2date
num2date(1e6, 'seconds since 1970-01-01')
```

Sorry again for abusing your kindness.

**Comment by SGhZD** [comment]
I have the same issue. cftime is the problem. I ran these lines and I got this error
```
TypeError                                 Traceback (most recent call last)
Cell In[1], line 16
     13 cftime.__version__
     15 from netCDF4 import num2date
---> 16 num2date(1e6, 'seconds since 1970-01-01')

File src\cftime\_cftime.pyx:535, in cftime._cftime.num2date()

File src\cftime\_cftime.pyx:379, in cftime._cftime.cast_to_int()

TypeError: '<' not supported between instances of 'numpy.longdouble' and 'int'

```

**Comment by joaohenry23** [comment]
Hi @SGhZD , could you share me the return of:

`import cftime
cftime.__version__`

I want to know If the problem is the version of cftime
